export enum COLORS {
    PINK = '#F7C0C4',
    YELLOW = '#FFF7B2',
    TEXT_IN_PINK = '#C05959',
    TEXT_IN_YELLOW = '#AB733F',
    BLUE_ICON = '#538DBE',
    GREY_TIP = '#979D9F',
    YELLOW_MESSAGE = '#FFFBD8',
    PROFILE = '#ACC0DD',
    NOTICE = '#FC5757',
    WHITE = '#FFFFFF',
    BLUE_BACKGROUND = '#759FC9',
}