export enum FLAGS {
    flagAustralia = require('./flags/Australia.svg'),
    flagArmenia = require('./flags/Armenia.svg'),
    flagBelarus = require('./flags/Belarus.svg'),
    flagBrazil = require('./flags/Brazil.svg'),
    flagCanada = require('./flags/Canada.svg'),
    flagFrance = require('./flags/France.svg'),
    flagGermany = require('./flags/Germany.svg'),
    flagIndia = require('./flags/India.svg'),
    flagItaly = require('./flags/Italy.svg'),
    flagJapan = require('./flags/Japan.svg'),
    flagChina = require('./flags/Republic_of_China.svg'),
    flagRussia = require('./flags/Russia.png'),
    flagSpain = require('./flags/Spain.svg'),
    flagSwitzerland = require('./flags/Switzerland.svg'),
    flagTurkey = require('./flags/Turkey.svg'),
    flagUK = require('./flags/UK.svg'),
    flagUkraine = require('./flags/Ukraine.svg'),
    flagUSA = require('./flags/USA.svg'),
    flagVietnam = require('./flags/Vietnam.svg'),
}

export const COUNTRIES = [
    {country: 'Australia', fl: FLAGS.flagAustralia}, 
    {country: 'Armenia', fl: FLAGS.flagArmenia},
    {country: 'Belarus', fl: FLAGS.flagBelarus},
    {country: 'Brazil', fl: FLAGS.flagBrazil},
    {country: 'Canada', fl: FLAGS.flagCanada},
    {country: 'France', fl: FLAGS.flagFrance},
    {country: 'Germany', fl: FLAGS.flagGermany},
    {country: 'India', fl: FLAGS.flagIndia},
    {country: 'Italy', fl: FLAGS.flagItaly},
    {country: 'Japan', fl: FLAGS.flagJapan},
    {country: 'Republic_of_China', fl: FLAGS.flagChina},
    {country: 'Russia', fl: FLAGS.flagRussia},
    {country: 'Spain', fl: FLAGS.flagSpain},
    {country: 'Switzerland', fl: FLAGS.flagSwitzerland},
    {country: 'Turkey', fl: FLAGS.flagTurkey},
    {country: 'UK', fl: FLAGS.flagUK},
    {country: 'Ukraine', fl: FLAGS.flagUkraine},
    {country: 'USA', fl: FLAGS.flagUSA}, 
    {country: 'Vietnam', fl: FLAGS.flagVietnam}, 
]