export enum FLAGS {
    flagAustralia = require('./flags/Australia.svg'),
    flagArmenia = require('./flags/Armenia.svg'),
    flagBelarus = require('./flags/Belarus.svg'),
    flagBrazil = require('./flags/Brazil.svg'),
    flagCanada = require('./flags/Canada.svg'),
    flagFrance = require('./flags/France.svg'),
    flagGermany = require('./flags/Germany.svg'),
    flagIndia = require('./flags/India.svg'),
    flagItaly = require('./flags/Italy.svg'),
    flagJapan = require('./flags/Japan.svg'),
    flagChina = require('./flags/Republic_of_China.svg'),
    flagRussia = require('./flags/Russia.svg'),
    flagSpain = require('./flags/Spain.svg'),
    flagSwitzerland = require('./flags/Switzerland.svg'),
    flagTurkey = require('./flags/Turkey.svg'),
    flagUK = require('./flags/UK.svg'),
    flagUkraine = require('./flags/Ukraine.svg'),
    flagUSA = require('./flags/USA.svg'),
    flagVietnam = require('./flags/Vietnam.svg'),
}