export enum ICONS {
    imgAddGlideMessage = require('./icons/add_glide_message.svg'),
    imgBackArrow = require('./icons/back_arrow.svg'),
    imgBlacklist = require('./icons/blacklist.svg'),
    imgChatMessage = require('./icons/chat_message.svg'),
    imgDeleteFromBlacklist = require('./icons/delete_from_blacklist.svg'),
    imgDownArrow = require('./icons/down_arrow.svg'),
    imgGlideMessage = require('./icons/glide_message.svg'),
    imgKeepNewCompanion = require('./icons/keep_new_companion.svg'),
    imgNoPhotoGlideMessage = require('./icons/no_photo_glide_message.svg'),
    imgNoPhotoInList = require('./icons/no_photo_in_list.svg'),
    imgNoPhotoProfile = require('./icons/no_photo_profile.svg'),
    imgPaperClip = require('./icons/paper_clip.svg'),
    imgSaveChanges = require('./icons/save_changes.svg'),
    imgSendGlideMessage = require('./icons/send_glide_message.svg'),
    imgSettings = require('./icons/settings.svg'),
    imgSkipGlideMessage = require('./icons/skip_glide_message.svg'),
    imgSmile = require('./icons/smile.svg'),
}