export enum ICONS {
    imgAddGlideMessage = require('./icons/add_glide_message.png'),
    imgBackArrow = require('./icons/back_arrow.png'),
    imgBlacklist = require('./icons/blacklist.png'),
    imgChatMessage = require('./icons/chat_message.png'),
    imgDeleteFromBlacklist = require('./icons/delete_from_blacklist.png'),
    imgDownArrow = require('./icons/down_arrow.png'),
    imgGlideMessage = require('./icons/glide_message.png'),
    imgKeepNewCompanion = require('./icons/keep_new_companion.png'),
    imgNoPhotoGlideMessage = require('./icons/no_photo_glide_message.png'),
    imgNoPhotoInList = require('./icons/no_photo_in_list.png'),
    imgNoPhotoProfile = require('./icons/no_photo_profile.png'),
    imgPaperClip = require('./icons/paper_clip.png'),
    imgSaveChanges = require('./icons/save_changes.png'),
    imgSendGlideMessage = require('./icons/send_glide_message.png'),
    imgSettings = require('./icons/settings.png'),
    imgSkipGlideMessage = require('./icons/skip_glide_message.png'),
    imgSmile = require('./icons/smile.png'),
}