export enum LANGUAGES {
    CHINESE = 'Chinese',
    ENGLISH = 'English',
    SPANISH = 'Spanish',
    ARABIAN = 'Arabian',
    RUSSIAN = 'Russian',
    PORTUGUESE = 'Portuguese',
    FRENCH = 'French',
    GERMAN = 'German',
    HINDI = 'Hindi',
    BENGALI = 'Bengali',
    JAPANESE = 'Japanese',
    ITALIAN = 'Italian',
    BELARUSIAN = 'Belarusian',
    UKRAINIAN = 'Ukrainian',
    VIETNAMESE = 'Vietnamese',
    ARMENIAN = 'Armenian',
    TURKISH = 'Turkish',
}